### ISSUE TITLE
Topics list by priority

### ISSUE THREAD

**Issue by WilliamTales** [Ilhasoft/rapidpro-docs#6]
1 - Channels Introduction
2 - Contact Introduction

- Adding New Fields
- Editing the Fields Value
- Looking for Contacts
- Types of Contacts and Variables

3 - Groups Introduction

- Creating a Group
- Adding or Removing a contact from a group

4 - Introduction to Flow

- Know the Flow Editor
- Creating a New Flow
- Types of Flows
- Creating a Flow in Different Languages
- Action Sets (commands)
- Rule Sets
- Sending a Message Through the Flow
- Adding and Actualizing the Contact Fields
- Classifying Contacts in Groups
- Adding Labels to Responses
- Response Rule
- Introduction to Flow Variables
- Referencing to RapidPro Variables
- Starting a Webhook
- Starting a Flow
- Starting Another Flow
- Start Someone Else in Flow
- Sending an Email
- Visualizing and Exporting Variables
- Exporting a Flow
- Importing a Flow

5 - Introduction to Triggers

- Creating a Message Keyword that Launches a Flow
- Creating a Message Keyword that Allows People to Join a Group
- Start a Flow in the Future or on a Schedule
- Start a Flow After Receiving a Call
- Start a Flow After a Missed Call
- Start a Flow When a Conversation is Started by a Contact
- Start a Flow After Receiving a Message Not Handled Elsewhere
- Ignoring a Keyword in a Flow

6 - Expressions
7 - Campaign Introduction

**Comment by johncordeiro** [comment]
Suggestions:

- Getting Started: Workspace overview (topics review)
- E-mail channel (less priority)
- NLU (less priority)

**Comment by johncordeiro** [comment]
New topic: `Best practices`
